{% set version = "1.0.2" %}

package:
  name: vulcan
  version: '{{version}}'

source:
  url: 'https://gitlab.com/treangenlab/vulcan/-/archive/v{{version}}/vulcan-v{{version}}.tar.gz'
  sha256: af9de0848f923df06839dbd81fe6e84c50760b7a9dd46122bc0cd1974ade9d2b 

build:
  noarch: generic
  number: 0
  script: mkdir -p ${PREFIX}/bin && cp vulcan ${PREFIX}/bin

requirements:
  run:
    - pysam
    - python >=3.5
    - minimap2
    - tqdm
    - ngmlr
    - samtools ==1.9
    - bamtools
    - numpy

test:
  source_files:
    - test
    - test/*
  commands:
    - vulcan --help 

about:
  home: https://gitlab.com/treangenlab/vulcan
  license: MIT
  license_file: LICENSE
  summary: vulcan, map long reads and prosper🖖, a long read mapping pipeline that melds minimap2 and NGMLR
